language: objective-c
osx_image: xcode7.3
cache: cocoapods
rvm:
- 2.2
podfile: Sensorama/Podfile
script:
#- ./scripts/travis_script.sh
- ./scripts/script_with_folds
addons:
  ssh_known_hosts:
  - gitlab.com
